name: seemur
description: Seemur version IOS

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  loading: ^1.0.2
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  intro_slider: ^2.2.8
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+4
  flutter_auth_buttons: ^0.6.0
  flutter_webview_plugin: ^0.3.10+1
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.5.0
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.1
  smooth_star_rating: ^1.0.4+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Recurso 1.png"
  adaptive_icon_background: "assets/icon/Recurso 1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logoblanco.png
     - assets/images/seemurIsotipo.png
     - assets/images/gif/seemurapp.gif
     - assets/images/gif/seemurapp2.gif
     - assets/images/gif/seemurapp3.gif
     - assets/images/icons/afternoonIcon@3x.png
     - assets/images/icons/barIcon@3x.png
     - assets/images/icons/beerIcon@3x.png
     - assets/images/icons/chaletIcon@3x.png
     - assets/images/icons/clubsIcon@3x.png
     - assets/images/icons/coffeeIcon@3x.png
     - assets/images/icons/eatOutIcon@3x.png
     - assets/images/icons/gastroPubIcon@3x.png
     - assets/images/icons/hostelIcon@3x.png
     - assets/images/icons/hotelFoodIcon@3x.png
     - assets/images/icons/hotelIcon@3x.png
     - assets/images/icons/icreamIcon@3x.png
     - assets/images/icons/innIcon@3x.png
     - assets/images/icons/partiyingIcon@3x.png
     - assets/images/icons/restaurantsIcon@3x.png
     - assets/images/icons/restingIcon@3x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
  fonts:
     - family: HankenGrotesk
       fonts:
         - asset: assets/fonts/HankenGrotesk-Regular.ttf
         - asset: assets/fonts/HankenGrotesk-Bold.ttf

         - asset: assets/fonts/HankenGrotesk-Light.ttf

         - asset: assets/fonts/HankenGrotesk-Black.ttf
         - asset: assets/fonts/HankenGrotesk-ExtraLight.ttf
         - asset: assets/fonts/HankenGrotesk-Medium.ttf
         - asset: assets/fonts/HankenGrotesk-SemiBold.ttf
     - family: OpenSans
       fonts:
         - asset: assets/fonts/OpenSans-Bold.ttf
         - asset: assets/fonts/OpenSans-BoldItalic.ttf
         - asset: assets/fonts/OpenSans-ExtraBold.ttf
         - asset: assets/fonts/OpenSans-ExtraBold.ttf
         - asset: assets/fonts/OpenSans-Italic.ttf
         - asset: assets/fonts/OpenSans-Light.ttf
         - asset: assets/fonts/OpenSans-LightItalic.ttf
         - asset: assets/fonts/OpenSans-Regular.ttf
         - asset: assets/fonts/OpenSans-SemiBold.ttf
         - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
